### ISSUE TITLE
[Google Reverse Image Search API] `original` and `title` fields missing for `inline_images`

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1296]
A customer reported that in the response from our Google Reverse Image Search API, the `original` filed is missing for `inline_images`. The `title` field is missing as well. I was able to reproduce it in the Playground:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/13686d2d-92f3-4550-baeb-8103a723fbb3)

[Playground](https://serpapi.com/playground?engine=google_reverse_image&image_url=https%3A%2F%2Fi.imgur.com%2FHBrB8p0.png) | [Inspect](https://serpapi.com/searches/657bf26eaa6c95d671a19dbc/inspect)

Documentation:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/63343b31-4f62-43a8-85ef-b09881096f98)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000052812?view=List)

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055363?view=List)

**Comment by martin-serpapi** [comment]
Another customer reported this. 

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056601?view=List)

**Comment by djsegal** [comment]
For clarity, I think this is two separate issues

We are now getting these errors on master:

```
Run bundle exec turbo_tests -n 6 spec/search/google_reverse_image
6 processes for 9 specs, ~ 2 specs per process

Randomized with seed 33[7](https://github.com/serpapi/SerpApi/actions/runs/7457088217/job/20288728192#step:4:8)9

....................................................................................F..................................................................................................F.....................................................................................................................................................................................FFF...........................................................................

Failures:

  1) Google Reverse Image API Reverse image results for `tomb raider`, filepath: spec/data/google_reverse_image/reverse-image-tomb-raider-63df09ef944[8](https://github.com/serpapi/SerpApi/actions/runs/7457088217/job/20288728192#step:4:9)[9](https://github.com/serpapi/SerpApi/actions/runs/7457088217/job/20288728192#step:4:10)31e5[11](https://github.com/serpapi/SerpApi/actions/runs/7457088217/job/20288728192#step:4:12)c1170-2023-02-05.html image_results has date for at least one result
     Failure/Error: image_results_with_date.should be_present
       expected `[].present?` to be truthy, got false
     # ./spec/search/google_reverse_image/reverse_image_tomb_raider_spec.rb:42:in `block (5 levels) in <main>'
     # ./vendor/bundle/ruby/2.7.0/gems/webmock-3.9.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  2) Google Reverse Image API Reverse image results for `tomb raider`, filepath: spec/data/google_reverse_image/reverse-image-tomb-raider.html image_results has date for at least one result
     Failure/Error: image_results_with_date.should be_present
       expected `[].present?` to be truthy, got false
     # ./spec/search/google_reverse_image/reverse_image_tomb_raider_spec.rb:42:in `block (5 levels) in <main>'
     # ./vendor/bundle/ruby/2.7.0/gems/webmock-3.9.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  3) Reverse Image API image_results, filepath: spec/data/google/reverse-image-pixel-5-mobile.html have date
     Failure/Error: @result_with_date_and_resolution[:date].should match(/\d{1,2} [a-zA-Z]{3,4}\. \d{4}/)

     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./spec/search/google_reverse_image/reverse_image_date_spec.rb:13:in `block (4 levels) in <main>'
     # ./vendor/bundle/ruby/2.7.0/gems/webmock-3.9.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  4) Reverse Image API image_results, filepath: spec/data/google/reverse-image-pixel-5-mobile.html does not include separator in date
     Failure/Error: @result_with_date_and_resolution[:date].should_not include "·"

     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./spec/search/google_reverse_image/reverse_image_date_spec.rb:17:in `block (4 levels) in <main>'
     # ./vendor/bundle/ruby/2.7.0/gems/webmock-3.9.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  5) Reverse Image API image_results, filepath: spec/data/google/reverse-image-pixel-5-mobile.html have image_resolution
     Failure/Error: @result_with_date_and_resolution[:image_resolution].should match(/\d+ × \d+/)

     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./spec/search/google_reverse_image/reverse_image_date_spec.rb:21:in `block (4 levels) in <main>'
     # ./vendor/bundle/ruby/2.7.0/gems/webmock-3.9.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 15.71 seconds (files took 13.15 seconds to load)
443 examples, 5 failures, 2 errors occurred outside of examples

Failed examples:

rspec ./spec/search/google_reverse_image/reverse_image_tomb_raider_spec.rb:40 # Google Reverse Image API Reverse image results for `tomb raider`, filepath: spec/data/google_reverse_image/reverse-image-tomb-raider-63df09ef9448931e511c1170-2023-02-05.html image_results has date for at least one result
rspec ./spec/search/google_reverse_image/reverse_image_tomb_raider_spec.rb:40 # Google Reverse Image API Reverse image results for `tomb raider`, filepath: spec/data/google_reverse_image/reverse-image-tomb-raider.html image_results has date for at least one result
rspec ./spec/search/google_reverse_image/reverse_image_date_spec.rb:[12](https://github.com/serpapi/SerpApi/actions/runs/7457088217/job/20288728192#step:4:13) # Reverse Image API image_results, filepath: spec/data/google/reverse-image-pixel-5-mobile.html have date
rspec ./spec/search/google_reverse_image/reverse_image_date_spec.rb:[16](https://github.com/serpapi/SerpApi/actions/runs/7457088217/job/20288728192#step:4:17) # Reverse Image API image_results, filepath: spec/data/google/reverse-image-pixel-5-mobile.html does not include separator in date
rspec ./spec/search/google_reverse_image/reverse_image_date_spec.rb:[20](https://github.com/serpapi/SerpApi/actions/runs/7457088217/job/20288728192#step:4:21) # Reverse Image API image_results, filepath: spec/data/google/reverse-image-pixel-5-mobile.html have image_resolution
```
